@default_files = ('main.tex');
$out_dir = 'out';
$aux_dir = 'out';

$pdflatex = 'lualatex -shell-escape';
$pdf_mode = 1;   
$bibtex = 'biber';   
$use_biber = 1;

$latex = 'lualatex %O %S';
$bibtex_use = 2; 